beachhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bnb.urls'), name='bnb_urls')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bnb/urls.py
from django.urls import path
from .views import HouseListView, BookingList, BookingViwe, HouseDetailViwe

app_name = 'bnb'

urlpatterns = [
    path('house_list/', HouseListView.as_view(), name='HouseListView'),
    path('booking_list/', BookingList.as_view(), name='BookingList'),
    path('book/', BookingViwe.as_view(), name='BookingViwe'),
    path('house/<category>', HouseDetailViwe.as_view(), name='HouseDetailViwe')
]

bnb/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils import timezone
from django.conf import settings


# Setting the house categoryes and to
# create a house with a sertian number of beds


class House(models.Model):
    HOUSE_CATEGORIES = (
        ('BAS', 'BASIC'),
        ('LUX', 'LUXURIUS'),
        ('KIN', 'KING'),
        ('QUE', 'QUEEN'),
    )
    number = models.IntegerField()
    category = models.CharField(max_length=3, choices=HOUSE_CATEGORIES)
    beds = models.IntegerField()
    capacity = models.IntegerField()

    def __str__(self):
        return f'{self.number}. {self.category} with {self.beds} beds for {self.capacity} people'


# Making a booking for a user for a certain amount of time


class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f'{self.user} has booked {self.house} from {self.check_in} to {self.check_out}'

bnb/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, FormView, View
from .models import House, Booking
from .booking_form import AvailableForm
from bnb.booking_system.available import available


class HouseListView(ListView):
    model = House


class BookingList(ListView):
    model = Booking


class HouseDetailViwe(View):
    def get(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        form = AvailableForm()
        house_list = House.objects.filter(category=category)

        if len(house_list) > 0:
            house = house_list[0]
            house_category = dict(
                house.HOUSE_CATEGORIES).get(house.category, None)
            context = {
                'house_category': house_category,
                'form': form,
            }
            return render(request, 'house_detail_view.html', context)
        else:
            return HttpResponse('Category dose not exist')

    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        house_list = House.objects.filter(category=category)
        form = AvailableForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

        available_house = []
        for house in house_list:
            if available(house, data['check_in'], data['check_out']):
                available_house.append(house)

        if len(available_house) > 0:

            house = available_house[0]
            booking = Booking.objects.create(
                user=self.request.user,
                house=house,
                check_in=data['check_in'],
                check_out=data['check_out']
            )
            booking.save()
            return HttpResponse(booking)

        else:
            return HttpResponse('This catagory of house is booked')


# Too check if the house is available


class BookingViwe(FormView):
    form_class = AvailableForm
    template_name = 'availability_form.html'

    def form_valid(self, form):
        data = form.cleaned_data
        house_list = House.objects.filter(category=data['house_category'])
        available_house = []
        for house in house_list:
            if available(house, data['check_in'], data['check_out']):
                available_house.append(house)

        if len(available_house) > 0:

            house = available_house[0]
            booking = Booking.objects.create(
                user=self.request.user,
                house=house,
                check_in=data['check_in'],
                check_out=data['check_out']
            )
            booking.save()
            return HttpResponse(booking)

        else:
            return HttpResponse('This catagory of house is booked')

bnb/templates/availability_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book a house</title>
</head>
<body>
    <form action="" method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <button type="submit">Book house</button>

    </form>
    
</body>
</html>

bnb/templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>CodeStar Blog</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--Bootstarp library imported -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <body class="d-flex flex-column h-100 main-bg">
        
        <main class="flex-shrink-0 main-bg">
            {% block content %}
            <!-- Content Goes here -->
            {% endblock content %}
        </main>


        
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    </body>
</head>

bnb/templates/bnb/booking_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking</title>
</head>
<body>
    {% for booking in booking_list %}
    <h2>{{booking}}</h2>
    {% endfor %}
</body>
</html>

bnb/templates/bnb/house_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'bnb/css/style.css' %}">
    <title>Houselist</title>
</head>
<body>
    {% for house in house_list %}
    <h2>{{house}}</h2>
    {% endfor %}
</body>
</html>

bnb/templates/house_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <!--Bootstarp library imported -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
   
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'bnb/css/style.css' %}">
    
<body class="d-flex flex-column h-100 main-bg">
    <main class="flex-shrink-0 main-bg">
        <!-- Main Content -->
        <div class="container">
            <div class="row justify-content-center">

                <!-- Room Image -->
                <div class="col-2 image">
                    <img
                        src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
                </div>

                <!-- Room Details -->
                <div class="col">

                    <!-- Div 1: Back to Home -->
                    <div class="home">
                        <a href="{% url 'bnb:HouseListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
                    </div>
                    <div class="row justify-content-evenly">
                    <!-- Div 2: Room Information -->
                    <div class="col house-info">
                        <h1>{{house_category}}</h1>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                            numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                            veniam,
                            rerum repellendus magnam labore. </p>
                    </div>

                    <!-- Div 3: Room Booking Form -->
                    
                        <div class="col">
                        <form id="booking-form" action="" method="POST">

                            {% csrf_token %}

                            <!-- Check in Div -->
                            <div class="input-group flex-nowrap p-2">
                                <span class="input-group-text" id="addon-wrapping">Check in: </span>
                                <input type="datetime-local" id="id_check_in" name="check_in">
                            </div>
                            

                            <!-- Check out Div -->
                            <div class="input-group flex-nowrap p-2">
                                <span class="input-group-text" id="addon-wrapping">Check out: </span>
                                <input type="datetime-local" id="id_check_out" name="check_out">
                            </div>

                            <!-- Subnit Booking Div -->
                            <div class="input-group p-2">
                                <button class="btn btn-primary" type="submit">Book the House</button>
                            </div>

                        </form>
                        </div>
                    </div>

                </div> <!-- END Room Div -->

            </div> <!-- END Main Content Div -->
        </div>
    </main>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>

bnb/templates/house_list_view.html
{% extends "base.html" %}

{% block content %}

<!-- Main Content -->
<div class="content">

  <!-- Room Image -->
  <div class="image">
      <img
          src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
  </div>

  <!-- Room Details -->
  <div class="room">

      <!-- Div 1: Back to Home -->
      <div class="home">
          <a href="{% url 'bnb:HouseListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
      </div>

      <!-- Div 2: house Information -->
      <div class="house-info">
          <h1>{{house_category}}</h1>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
              numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
              veniam,
              rerum repellendus magnam labore. </p>
      </div>

      <!-- Div 3: Room Booking Form -->
      <form id="booking-form" action="" method="POST">

          {% csrf_token %}

          <!-- Input Div -->
          <div class="input-div">
              <label for="id_check_in">Check In : </label>
              <input type="datetime-local" id="id_check_in" name="check_in">
          </div>

          <!-- Input Div -->
          <div class="input-div">
              <label for="id_check_out">Check Out : </label>
              <input type="datetime-local" id="id_check_out" name="check_out">
          </div>

          <!-- Input Div -->
          <div class="input-div">
              <button type="submit">Book the Room</button>
          </div>

      </form>

  </div> <!-- END Room Div -->

</div> <!-- END Main Content Div -->


{% endblock %}